version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: pba-mysql
    restart: always
    environment:
      MYSQL_DATABASE: planbook_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: pba_user
      MYSQL_PASSWORD: pba_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pba-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql-db

volumes:
  db_data: